"""Add month

Revision ID: 9996fc27efde
Revises: 
Create Date: 2025-07-29 21:32:12.815987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9996fc27efde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('month', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.drop_column('month')

    # ### end Alembic commands ###
